#!/bin/sh

# This file is part of Openflorian.
# 
# Copyright (C) 2015  Bastian Kraus
# 
# Openflorian is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version)
#     
# Openflorian is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#     
# You should have received a copy of the GNU General Public License
# along with Openflorian.  If not, see <http://www.gnu.org/licenses/>.

# Openflorian Trigger Button Listener rc.d handler
# @author Bastian Kraus <bofh@k-hive.de>

### BEGIN INIT INFO
# Provides:          Slotmachine Trigger
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Slotmachine Trigger Watchdog fuer /dev/input/eventX
# Description:       
### END INIT INFO

### CONFIGURATION
### Modify this path to the directory where the trigger jar and the config file is in
basepath="/home/pi/slotmachine-java"

pidfile="$basepath/slotmachine-trigger.pid";
startcmd='java -jar $basepath/slotmachine-trigger-0.1-DEV.jar -c $basepath/config.properties &';

# set current working directory
cd "$basepath";

# Actions
case "$1" in
    start)
        # START
        echo "Starting slotmachine-trigger service...";
        if ! $(cat "$pidfile" 2>/dev/null) || ! $( kill -0 $(cat "$pidfile") 2>/dev/null ) ; then
                eval $startcmd;
                echo $! > "$pidfile";
                echo "Slotmachine trigger service started with pid: $(cat "$pidfile")";
            else
                echo "Slotmachine trigger service already running with PID: $(cat "$pidfile")";
        fi
        ;;
    stop)
        # STOP
        echo "Stopping Slotmachine Trigger Service with pid: $(cat "$pidfile")...";
        pid=$(cat "$pidfile")
        if  $(kill -0 $(cat "$pidfile") 2>/dev/null ) ; then
                kill -15 $pid;
                rm -f $pidfile;
                echo "... stopped!";
        else
                echo "... no process with pid $pid found!";
        fi
        ;;
    restart)
        # RESTART
        $0 stop;
        $0 start;
        ;;
	*)
        echo "Usage: /etc/init.d/slotmachine {start|stop|restart}"
        exit 1
        ;;
esac

exit 0